# .github/workflows/run_vp_predictions_daily.yml

name: Run Vp Predictions

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes for testing

jobs:
  test-cron:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Cron job ran successfully!"
