# .github/workflows/run_vp_predictions_daily.yml

name: Run Vp Predictions

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes for testing

jobs:
  run-vp-preds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["pypy3.10", "3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install copernicusmarine
      - name: Run run.sh
        run: sh ./run.sh
